### ISSUE TITLE
Authentication failed with "This app is blocked" error

### ISSUE THREAD

**Issue by pklion** [murataya/o2popper#4]
![image](https://user-images.githubusercontent.com/78145811/182598741-5ef6698c-891d-4bde-a66d-44e5dedf922f.png)

O2Popper で 認可 ボタンを押すと、アカウントを選択したところで上の画面が出て認証ができません。
ちなみに、 O2Popper に標準で組み込まれているシークレットファイルを利用しています。

**Comment by murataya** [comment]
申し訳ございません。

組み込みのシークレット ファイル内で使用している
OAuth2 用の クライアント ID と クライアント シークレット ですが、
無料で使用できるユーザー数の上限である 100 人 に達したため、
新規ユーザー様はご自身で
クライアント ID と クライアント シークレット を発行して
いただかなければ利用できなくなりました。

クライアント ID と クライアント シークレットは
Google Cloud Platform (https://console.cloud.google.com)
にて無料で発行可能です。
※ 手順を間違うと有料版になって課金されてしまうらしいので、ご注意ください。

発行手順はネットで検索してもらえれば見つかります。
（時間がとれたら発行手順のドキュメントを作成したいと考えています。）

ご自身で クライアント ID と クライアント シークレット を
発行したくないという場合は、他のメールソフトに
組み込まれている クライアント ID と クライアント シークレットを
使用して回避するという方法もあります。
こちらの回避方法については作者までメールでお問い合わせください。

**Comment by pklion** [comment]
了解しました。ありがとうございました。
